### ISSUE TITLE
Error on querying version

### ISSUE THREAD

**Issue by code2be** [anhdhbn/telebit#2]
When try to `./telebit version`, I get:
```code2be@ahmed-dell:~$ ./telebit status
/home/code2be/Applications/telebit/bin/telebit-remote.js:643
  var verstrd = [ pkg.name + ' daemon v' + state.config.version ];
                                                        ^

TypeError: Cannot read property 'version' of undefined
    at handleConfig (/home/code2be/Applications/telebit/bin/telebit-remote.js:643:57)
    at /home/code2be/Applications/telebit/bin/telebit-remote.js:359:22
    at /home/code2be/Applications/telebit/usr/share/install-launcher.js:241:26
    at ChildProcess.exithandler (child_process.js:280:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)```

**Comment by ixxvivxxi** [comment]
This always happens to me after rebooting the laptop when starting telebit. I have to reinstall it again.

**Comment by ricardoamaro** [comment]
This works for me on Linux without needing to reinstall:

```
export XDG_RUNTIME_DIR=/run/user/$UID
systemctl --user restart telebit
```
(wait a few seconds)

```
~/Applications/telebit/bin/telebit http 8000
telebit remote v0.20.8 (--config '~/.config/telebit/telebit.yml')

> Forwarding https://......... => localhost:8000
```

**Comment by nisone** [comment]
> This works for me on Linux without needing to reinstall:
> 
> ```
> export XDG_RUNTIME_DIR=/run/user/$UID
> systemctl --user restart telebit
> ```
> 
> (wait a few seconds)
> 
> ```
> ~/Applications/telebit/bin/telebit http 8000
> telebit remote v0.20.8 (--config '~/.config/telebit/telebit.yml')
> 
> > Forwarding https://......... => localhost:8000
> ```

this works for me. Thanks

**Comment by edewit** [comment]
I get this when I try to install telebit:
```bash
$> curl https://get.telebit.io/ | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2126  100  2126    0     0   2397      0 --:--:-- --:--:-- --:--:--  2396

Installing Telebit Remote to '/home/edewit/Applications/telebit'
.........Something went wrong:
× telebit.service - Telebit Remote
     Loaded: loaded (/home/edewit/.config/systemd/user/telebit.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Sun 2024-09-01 17:45:53 CEST; 1s ago
   Duration: 37ms
       Docs: https://git.coolaj86.com/coolaj86/telebit.js/
    Process: 51461 ExecStart=/home/edewit/Applications/telebit/bin/node /home/edewit/Applications/telebit/bin/telebitd.js daemon --config /home/edewit/.config/telebit/telebitd.yml (code=exited, status=203/EXEC)
   Main PID: 51461 (code=exited, status=203/EXEC)
        CPU: 36ms

Sep 01 17:45:53 edewit-thinkpad systemd[2761]: telebit.service: Scheduled restart job, restart counter is at 3.
Sep 01 17:45:53 edewit-thinkpad systemd[2761]: telebit.service: Start request repeated too quickly.
Sep 01 17:45:53 edewit-thinkpad systemd[2761]: telebit.service: Failed with result 'exit-code'.
Sep 01 17:45:53 edewit-thinkpad systemd[2761]: Failed to start telebit.service - Telebit Remote.
.
/home/edewit/Applications/telebit/bin/telebit-remote.js:643
  var verstrd = [ pkg.name + ' daemon v' + state.config.version ];
                                                        ^

TypeError: Cannot read property 'version' of undefined
    at handleConfig (/home/edewit/Applications/telebit/bin/telebit-remote.js:643:57)
    at /home/edewit/Applications/telebit/bin/telebit-remote.js:359:22
    at /home/edewit/Applications/telebit/usr/share/install-launcher.js:241:26
    at ChildProcess.exithandler (child_process.js:280:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```
I get the same error when I try to use the npm package:

```bash
$> npm install telebit -g
$> npx telebit init
(unix socket: /home/edewit/.local/share/telebit/var/run/telebit.sock)

/home/edewit/.nvm/versions/node/v20.15.0/lib/node_modules/telebit/bin/telebit-remote.js:658
  var verstrd = [ pkg.name + ' daemon v' + state.config.version ];
```
Adding the `XDG_RUNTIME_DIR` as a variable doesn't seem to help, any ideas?

I'm using fedora linux 40

**Comment by xyvielyons** [comment]
this helped me thank you so much

**Comment by gromaxbro** [comment]
> I get this when I try to install telebit:
> 
> ```shell
> $> curl https://get.telebit.io/ | bash
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  2126  100  2126    0     0   2397      0 --:--:-- --:--:-- --:--:--  2396
> 
> Installing Telebit Remote to '/home/edewit/Applications/telebit'
> .........Something went wrong:
> × telebit.service - Telebit Remote
>      Loaded: loaded (/home/edewit/.config/systemd/user/telebit.service; enabled; preset: disabled)
>     Drop-In: /usr/lib/systemd/user/service.d
>              └─10-timeout-abort.conf
>      Active: failed (Result: exit-code) since Sun 2024-09-01 17:45:53 CEST; 1s ago
>    Duration: 37ms
>        Docs: https://git.coolaj86.com/coolaj86/telebit.js/
>     Process: 51461 ExecStart=/home/edewit/Applications/telebit/bin/node /home/edewit/Applications/telebit/bin/telebitd.js daemon --config /home/edewit/.config/telebit/telebitd.yml (code=exited, status=203/EXEC)
>    Main PID: 51461 (code=exited, status=203/EXEC)
>         CPU: 36ms
> 
> Sep 01 17:45:53 edewit-thinkpad systemd[2761]: telebit.service: Scheduled restart job, restart counter is at 3.
> Sep 01 17:45:53 edewit-thinkpad systemd[2761]: telebit.service: Start request repeated too quickly.
> Sep 01 17:45:53 edewit-thinkpad systemd[2761]: telebit.service: Failed with result 'exit-code'.
> Sep 01 17:45:53 edewit-thinkpad systemd[2761]: Failed to start telebit.service - Telebit Remote.
> .
> /home/edewit/Applications/telebit/bin/telebit-remote.js:643
>   var verstrd = [ pkg.name + ' daemon v' + state.config.version ];
>                                                         ^
> 
> TypeError: Cannot read property 'version' of undefined
>     at handleConfig (/home/edewit/Applications/telebit/bin/telebit-remote.js:643:57)
>     at /home/edewit/Applications/telebit/bin/telebit-remote.js:359:22
>     at /home/edewit/Applications/telebit/usr/share/install-launcher.js:241:26
>     at ChildProcess.exithandler (child_process.js:280:7)
>     at ChildProcess.emit (events.js:182:13)
>     at maybeClose (internal/child_process.js:962:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> ```
> 
> I get the same error when I try to use the npm package:
> 
> ```shell
> $> npm install telebit -g
> $> npx telebit init
> (unix socket: /home/edewit/.local/share/telebit/var/run/telebit.sock)
> 
> /home/edewit/.nvm/versions/node/v20.15.0/lib/node_modules/telebit/bin/telebit-remote.js:658
>   var verstrd = [ pkg.name + ' daemon v' + state.config.version ];
> ```
> 
> Adding the `XDG_RUNTIME_DIR` as a variable doesn't seem to help, any ideas?
> 
> I'm using fedora linux 40

did you found any solution?
